
@baseURL = http://localhost:4000/api
@id = 619596aa1ef3ee5198461280
###
// POST - Adiciona Filmes
POST {{baseURL}}/filmes/
Content-Type: application/json

{
   "genero": "",
   "nome": "",
   "diretor": "",
   "ano": "",
   "nota": "",
   "user_id": ""
}


### 
// DELETE - Apaga um filme através do id informado
DELETE {{baseURL}}/filmes/{{nome}}
Content-Type: application/json

###
// PUT - Altera um filme pelo nome
PUT {{baseURL}}/filmes/{{nome}}
Content-Type: application/json

{
    "nome": "",
    "email": "",
    "senha": "",
    "ativo": true
  }

